project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Bird Migration"
  author:
    - Joyce Robbins (jtr13)
    - Big Bird (bb1)
  repo-url: https://github.com/jtr13/birds
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


